# -*- coding: utf-8 -*-
"""Gradio-YOLONAS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gRvfNW5S3lhGrij4PVUahn1MmRXJ1tGE
"""

!pip install imutils
!pip install roboflow
!pip install pytube --upgrade

pip install super-gradients

!pip install torchinfo

pip install gradio

from super_gradients.training import models

import gradio as gr
from PIL import Image
import io
import os
# Load the YOLO NAS model
yolo_nas_l = models.get("yolo_nas_l", pretrained_weights="coco")

def yolo_nas_inference(image):
      print("IMAGE TYPE",type(image))
      print(image)
      pil_image = image.convert("RGB").resize((512, 512))
      yolo_nas_l.predict(pil_image, conf=0.30).save("./OUT")
      out = Image.open('./OUT/pred_0.jpg')
      location = "./OUT"
      file = './pred_0.jpg'
      path = os.path.join(location, file)
      os.remove(path)
      print(out)
      return out

inputs = gr.inputs.Image(type = 'pil',label="Input Image")
outputs = gr.outputs.Image(type = 'numpy',label="Output Image")
  # Create the Gradio interface
gr.Interface(yolo_nas_inference, inputs=inputs, outputs=outputs, title="YOLO NAS Object Detection").launch()

